### ISSUE TITLE
The page in the mobile browser has a white line at the bottom

### ISSUE THREAD

**Issue by thealek0** [thealek0/radio-ga-ga#13]
**Describe the bug**
The page in the mobile chrome has a white line at the bottom

**To Reproduce**
Scroll down page

**Expected behavior**
without scrolling

**Smartphone (please complete the following information):**
 - Device: [Honor 7x, Pixel]
 - OS: [Android]
 - Browser [chrome]
 - Version [>78]

**Comment by DimaHrist** [comment]
Can't reproduce in google chrome dev tools
