### ISSUE TITLE
101.ru not working

### ISSUE THREAD

**Issue by turbiddude** [thealek0/radio-ga-ga#37]
**To Reproduce**
1. Go to 'index.html'
2. Open Network tab
3. Click on 'Play'
4. See error in media request

**Screenshots**
![image](https://user-images.githubusercontent.com/33316505/73048819-6e4ae600-3e8b-11ea-9422-1a0dc9b8472e.png)

**Comment by thealek0** [comment]
Feel free to do PR

**Comment by thealek0** [comment]
#38
